use casper_types::ApiError;

#[repr(u16)]
#[derive(Clone, Copy)]
pub enum Error {
    InvalidAccount = 1,
    MissingInstaller = 2,
    InvalidContext = 3,
    InvalidIdentifierMode = 4,
    MissingTokenID = 5,
    InvalidTokenIdentifier = 6,
    FailedToGetArgBytes = 7,
    InvalidContractOwner = 8,
    RequestIdIlledFormat = 9,
    FailedToCreateDictionary = 10,
    RequestIdRepeated = 11,
    MissingKey = 12,
    SerilizationError = 13,
    UnlockIdRepeated = 14,
    FailedToCreateDictionaryUnlockIds = 15,
    ContractAlreadyInitialized = 16,
    CallerMustBeAccountHash = 17,
    TooManyTokenIds = 18,
    UnlockIdIllFormatted = 19,
    TxHashUnlockIdIllFormatted = 20,
    InvalidDev = 100,
    InvalidWrappedToken = 101,
    MissingContractOwner = 102,
    MissingDev = 103,
    MissingContractWhiteList = 400,
    InvalidContractWhitelist = 401,
    InvalidWhiteListAddress = 402,
    MissingTokenMetaData = 403,
    InvalidTokenMetaData = 404,
    MissingNewAddressWhitelist = 405,
    InvalidNewAddressWhitelist = 406,
    AddressRepeated = 407,
    MissingNftContractHash = 408,
    InvalidNftContractHash = 409,
    CannotGetWhitelistAddrressArg = 410,
    InputMustBeAccountHash = 411,
    AccountIllFormatted = 412,
    MissingNftOwner = 413,
    InvalidNftOwner = 414,
    MissingRequestId = 415,
    InvalidRequestId = 416,
    MissingNftContractPackage = 417,
    InvalidNftContractPackage = 418,
    MissingNumberOfTickets = 419,
    InvalidNumberOfTickets = 420,
    CannotGetNumberOfTickets = 421,
    CanotGetWhiteListNumber = 422,
    CanotGetNftMintedNumber = 423,
    ReachMaximumNumberOfMinting = 424,
    MissingCsprMintFee = 425,
    InvalidCsprMintFee = 426,
    CanNotGetContractPurse = 427,
    CanNotTransferCSPR = 428,
    MissingAmount = 429,
    InvalidAmount = 430,
    CannotGetAmount = 431,
    NotEnoughAmount = 432,
    MissingWcsprContract = 433,
    InvalidWcsprContract = 434,
    MissingFeeReceiver = 435,
    InvalidFeeReceiver = 436,
    MissingSrcPurse = 437,
    InvalidSrcPurse = 438,
    CanNotGetUserPurse = 439,
}

impl From<Error> for ApiError {
    fn from(e: Error) -> Self {
        ApiError::User(e as u16)
    }
}
